pipeline {
    // 1. Agent: Use the official Python Playwright Docker image
    agent {
        docker {
            image 'mcr.microsoft.com/playwright/python:latest'
            args '--shm-size=2g'
        }
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo "Fetching code from GitHub..."
                // Use your specific credentials ID for your GitHub PAT
                git credentialsId: 'github-pat', url: 'https://github.com/Sindhura18/Playwright.git'
            }
        }

        stage('Install & Run Tests') {
            steps {
                sh """
                # 1. Install dependencies from requirements.txt
                pip install -r requirements.txt

                # 2. Run tests using pytest
                # --junitxml saves the test results in XML format for Jenkins to read
                # --html is optional and requires specific pytest-html configuration
                pytest tests/ --junitxml=test-results/junit-report.xml
                """
            }
        }
    }

    // Post-build actions for reporting and cleanup
    post {
        always {
            // 1. Publish JUnit results for native Jenkins reporting (Pass/Fail)
            junit 'test-results/junit-report.xml'

            // 2. Publish the detailed HTML report (if generated by pytest-html or playwright config)
            publishHTML(target: [
                allowMissing: true, // Allow missing if tests fail and no report is generated
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'playwright-report', // Check where your HTML report is saved
                reportFiles: 'index.html',
                reportName: 'Playwright HTML Report'
            ])

            // 3. Archive logs, screenshots, or videos generated during the run
            archiveArtifacts artifacts: '**/*.log, **/*.png', fingerprint: true
        }
        success {
            echo "Pipeline finished successfully. Checking results in Grafana."
        }
        failure {
            echo "Tests failed. Review JUnit report and HTML report for details."
        }
        cleanup {
            // 4. Clean up the Jenkins workspace to save disk space
            cleanWs()
        }
    }
}
